### ISSUE TITLE
getProducts & getSubscriptions returning both products and subscriptions

### ISSUE THREAD

**Issue by a-koka** [dooboolab/react-native-iap#1167]
### Version of react-native-iap
5.0.1

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Behavior
Unlike the naming and the documentation states, `getProducts` & `getSubscriptions` are returning both products and subscriptions.

**Comment by andordavoti** [comment]
Having the same issue. On iOS the subscriptions show up in the products. On android it's working fine.

**Comment by hyochan** [comment]
You are right! In `iOS` they treat them the same. Currently, you may separate arrays for items on `subscription` and `products`.

**Comment by rwichmann** [comment]
I can confirm this on iOS with version `4.6.3`.

My observation:
If you fetch subscriptions with `RNIap.getSubscriptions(['id1', 'id2'])`
You will get the same subscriptions when calling `RNIap.getProducts([])` with an empty array.

So filtering product IDs for fetching does not solve the issue. You will need to filter the results after fetching.

**Comment by rusakovic** [comment]
Fixed in `6.0.1` version. Issue could be closed

**Comment by andresesfm** [comment]
Closing as solved, thank you

**Comment by Mihai-github** [comment]
The problem still existing even if try like this:

```
RNIap.getProducts([])
RNIap.getSubscriptions([])
```
OR WITH IDS THE RETURNED VALUE IS [].
