### ISSUE TITLE
purchaseUpdateListener getting called 100+ times, but not every app run

### ISSUE THREAD

**Issue by aciereszko** [dooboolab/react-native-iap#1579]
> Please use [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want get some help out of it. 

purchaseUpdateListener, gets called 100+ times - sometimes. The behavior is really strange. On one app start it will get called 0 times after the initial setup. I'll kill the app and restart it, I'll get 65 calls to the purchaseUpdateListener. I'll kill the app a few more times, 0 calls to purchaseUpdateListener. Then the next run 140 calls to purchaseUpdateListener. I do call finishTransaction... But I don't understand the intermittant nature of this problem. Sandobox env. Confirmed using two different sandbox users.

The issue is that I am not sure when I should validate my receipt. I thought purchaseUpdateListener is the place, but now when It gets called hundreds of times...

I looked at these:

https://github.com/dooboolab/react-native-iap/issues/1104

https://github.com/dooboolab/react-native-iap/issues/1172

But those did not help me.

### Version of react-native-iap
7.3.0

### Version of react-native
0.63.4

### Platforms you faced the error (IOS or Android or both?)
iOS (not tested on Android)

### Expected behavior

If no new store events happen (the test users have not renewed or purchased anything in the  last few days), I should not be seeing any calls to purchase UpdateListener.

### Actual behavior

I see a lot of calls to purchaseUpdateListener, but not consistently

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

```
import { DatePickerIOSBase, Platform } from "react-native";
import { debug } from "react-native-reanimated";

import storeAuth from "../config/storeAuth";
import { debugLog, errorType } from "../utils/LoggingUtils";

const {
  initConnection,
  getSubscriptions,
  validateReceiptIos,
  getPurchaseHistory,
  flushFailedPurchasesCachedAsPendingAndroid,
  clearTransactionIOS,
  endConnection,
  purchaseUpdatedListener,
  purchaseErrorListener,
  finishTransaction,
  requestSubscription,
  presentCodeRedemptionSheetIOS,
} = require("react-native-iap");

const androidValidationURL =
  "https://xxxx.cloudfunctions.net/validate";

let purchaseUpdatedListenerHandler = undefined;
let purchaseErrorListenerHandler = undefined;

const subscriptionStatus = {
  EXPIRED: "expired",
  VALID: "valid",
  NONE: "none",
};

const subcriptionSKUs = Platform.select({
  ios: ["xxx1", "xxx2"],
  android: ["xxx1", "xxx2"],
});

const initIAP = (onPurchaseUpdate, onInitComplete, onError) => {
  initConnection()
    .then(() => {

      purchaseUpdatedListenerHandler = purchaseUpdatedListener(
        async (purchase) => {

          if (purchase.transactionReceipt) {
            const result = await finishTransaction(purchase);
            onPurchaseUpdate(purchase);
          } else {
            onError(
              "RNIap.purchaseUpdatedListener. start: purchase.transactionReceipt: false",
              "",
              errorType.WARNING
            );
          }
        }
      );

      purchaseErrorListenerHandler = purchaseErrorListener(async (err) => {
        onError("RNIap.purchaseErrorListener. start ", err, type);
      });

      onInitComplete();
    })
    .catch((err) => {
      //initConnection
      onError("RNIap.initConnection.catch: ", err, errorType.WARNING);
    });
};

/**
 * Cleans up all subscriptions
 */
export const releaseIAP = async () => {
  if (purchaseUpdatedListenerHandler) {
    purchaseUpdatedListenerHandler.remove();
    purchaseUpdatedListenerHandler = undefined;
  }
  if (purchaseErrorListenerHandler) {
    purchaseErrorListenerHandler.remove();
    purchaseErrorListenerHandler = undefined;
  }
  endConnection()
    .then(() => {
    })
    .catch((err) => {
    });
};

const fetchActiveSubscriptions = (
  onSubscriptionsFetched,
  onValidationDone,
  onError
) => {
  flushTransactions()
    .then(() => {
      /*** GETS AVAILABLE SUBSCRIPTIONS ***/
      getSubscriptions(subcriptionSKUs)
        .then((res) => {
          onSubscriptionsFetched(res);
          /*** GETS PURCHASE HISTORY ***/
          //lets get the entire purchase history, get the latest receipt, and validate it
          getPurchaseHistory()
            .then((res) => {
              const lastPurchase =
                res.length === 0
                  ? undefined
                  : res.reduce((a, b) => {
                      return a.transactionDate > b.transactionDate ? a : b;
                    });

              /*** VALIDATE PURCHASE ***/
              validatePurchase(lastPurchase, onValidationDone, onError);
            })
            .catch((err) => {
              //getPurchaseHistory
              onError(
                "RNIap.getPurchaseHistory.catch: ",
                err,
                errorType.WARNING
              );
            });
        })
        .catch((err) => {
          //getSubscriptions
          onError("RNIap.getSubscriptions.catch: ", err, errorType.WARNING);
        });
    })
    .catch((err) => {
      //flushTransactions
      onError("RNIap.getPurchaseHistory.catch: ", err, errorType.WARNING);
    });
};

/**
 * Validates the receipt from the app/play store. Validation done using the app store api (no own validation for now)
 * @param {receipt} receipt as received from the app/play store
 */
const validatePurchase = async (purchase, onValidationDone, onError) => {
  if (!purchase) {
    //no transactions
    onValidationDone(subscriptionStatus.NONE, purchase);
  } else {
    const receipt = purchase.transactionReceipt;

    if (Platform.OS === "ios") {
      const receiptBodyiOS = {
        "receipt-data": receipt,
        password: storeAuth.iosAppStore.appAccessPassword,
      };

      const result = await validateReceiptIos(receiptBodyiOS, true)
        .then((res) => {
          //latest_receipt_info holds the entire purchase history
          const renewalHistory = res.latest_receipt_info;

          //we just need the renewal with the youngest expiration date
          const latestRenewal =
            renewalHistory.length === 0
              ? undefined
              : renewalHistory.reduce((a, b) => {
                  test.push(new Date(parseInt(a.expires_date_ms)));
                  return a.expires_date_ms > b.expires_date_ms ? a : b;
                });



          const expired = latestRenewal
            ? parseInt(res.receipt.request_date_ms) >
              parseInt(latestRenewal.expires_date_ms)
            : false;
          if (!expired) {
            onValidationDone(subscriptionStatus.VALID, purchase);
          } else {
            onValidationDone(subscriptionStatus.EXPIRED, purchase);
          }
        })
        .catch((err) => {
          onError("RNIap.validateReceiptIos.catch: ", err, errorType.WARNING);
        });
    } else if (Platform.OS === "android") {

      fetch(androidValidationURL, {
        headers: { "Content-Type": "application/json" },
        method: "POST",
        body: JSON.stringify({ data: receipt }),
      })
        .then((res) => {

          res.json().then((r) => {
            debugLog(
              "validatePurchase(): android: then: r: " + JSON.stringify(r)
            );
            if (r.result.error == -1) {
              onError(
                "Subscription Error. There has been an error with your subscription.",
                r.result.error,
                errorType.WARNING
              );
            } else if (r.result.isActiveSubscription == 1) {
              onValidationDone(subscriptionStatus.VALID, purchase);
            } else {
              onValidationDone(subscriptionStatus.EXPIRED, purchase);
            }
          });
        })
        .catch((err) => {
          onError(
            "validatePurchase(): android: catch: ",
            err,
            errorType.WARNING
          );
        });
    }
  }
};

/**
 * Cleans up all transactions. Meant to be called first, to flush out cancelled/stale transactions.
 */
const flushTransactions = async () => {
  if (Platform.OS === "android") {
    await flushFailedPurchasesCachedAsPendingAndroid();
  } else {
    await clearTransactionIOS();
  }
};

const purchaseSubscription = async (
  subscription,
  onSubscriptionRequest,
  onError
) => {
  onSubscriptionRequest();

  if (Platform.OS === "ios") {
    await clearTransactionIOS();
  }

  requestSubscription(subscription)
    .then(() => {
      debugLog("RNIap.requestSubscription success");
    })
    .catch((err) => {
      onError("RNIap.requestSubscription failed: ", err, errorType.WARNING);
    });
};

const useOfferCode = async () => {
  presentCodeRedemptionSheetIOS();
};

module.exports = {
  subscriptionStatus,
  initIAP,
  releaseIAP,
  fetchActiveSubscriptions,
  purchaseSubscription,
  useOfferCode,
};
```

**Comment by aciereszko** [comment]
I narrowed the problem down to a call to getPurchaseHistory(), if I call this after I wired up my purchaseUpdatedListener, this is when I get the flood of callbacks (now up to 450+) - and only once in every 4 app starts.

I did see that someone reported similar: https://github.com/dooboolab/react-native-iap/issues/1296

I'll try this workaround for iOS.

But a more general question, if we are supposed to be validating and storing the receipt in purchaseUpdateListener, and it would seem like getPurchaseHistory() causes these issues, what is the usage pattern for the library?

**Comment by adambeer** [comment]
Im getting this behavior without calling getPurchaseHistory() at all.

**Comment by aciereszko** [comment]
One thing that kind of helped me, is trying to reproduce/not reproduce the problem using their IAPExample. Helps me narrow down the problem in my own implementation. This library seems pretty flaky unfortunately :( 

Do you get this behavior if you just init connection, then wire up the listener. And that's it?

**Comment by adambeer** [comment]
In my example Im awaiting initConnection, awaiting clearTransactionIOS (im ios only) and then calling getSubscriptions.

Listeners are then wired up. Just a minute ago, I tested this in the sandbox and made a purchase which worked fine. (I also cancelled my subscription just before making the purchase this time) I refreshed the app and purchaseUpdatedListener fired 16 times. Because of the way my system is setup, the only negative side effect is 16 receipt validation calls to my backend but this is definitely an issue.

I havent played around with the IAPExample, but I have looked at it as a reference.

**Comment by adambeer** [comment]
If I had to make a guess here...purchaseUpdatedListener is firing off for all past purchases. In my situation Im just dealing with a single auto-renew subscription. So I am constantly cancelling and purchasing it. It almost seems as if some of the app builds that I send to my phone are clearing all of the past purchase transactions and then they all get sent to purchaseUpdatedListener

**Comment by aciereszko** [comment]
For me the listener now fires 450 times....

Do you see those same 16 transactions everytime you restart the app now? Every few restarts (for me it's like very 3-4 restarts) I found some posts saying that calling finishTransaction in the listener should help. But it doesn't for me.

If it does happen everytime or periodically, does it still happen if you don't call clearTransactionIOS() and don't call getSubscriptions (so just initConnection and just the wiring up of the listeners).

I feel like I'm stumbling in the dark trying to make this thing work.

**Comment by aciereszko** [comment]
One thing to consider is to go to revenuecat or iaphub. My demo implementations using those services have none of those problems. iaphub is the cheaper of the two, added benefit, you get their validation backends.

Alternatively, I'm evaluating this free alternative https://www.npmjs.com/package/expo-in-app-purchases so far so good, but I'm not done yet...

**Comment by aciereszko** [comment]
> If I had to make a guess here...purchaseUpdatedListener is firing off for all past purchases. In my situation Im just dealing with a single auto-renew subscription. So I am constantly cancelling and purchasing it. It almost seems as if some of the app builds that I send to my phone are clearing all of the past purchase transactions and then they all get sent to purchaseUpdatedListener

Maybe there is a way to filter out all those calls for past purchases. But that would require to validate the receipt I think, so that's moot.

**Comment by aciereszko** [comment]
> In my example Im awaiting initConnection, awaiting clearTransactionIOS (im ios only) and then calling getSubscriptions.
> 
> Listeners are then wired up. Just a minute ago, I tested this in the sandbox and made a purchase which worked fine. (I also cancelled my subscription just before making the purchase this time) I refreshed the app and purchaseUpdatedListener fired 16 times. Because of the way my system is setup, the only negative side effect is 16 receipt validation calls to my backend but this is definitely an issue.
> 
> I havent played around with the IAPExample, but I have looked at it as a reference.
> 
> Edit note: It looks like the transactionId's are all sequential too. But the originalTransactionIdentifierIOS for all of these events is the same.

So addressing your edit. This may be helpful, different ids would indicate renewals/restores:

Source: https://developer.apple.com/documentation/appstorereceipts/original_transaction_id

**Comment by adambeer** [comment]
This seems like its happening on expo's in-app-purchase module too: https://github.com/expo/expo/issues/11432

**Comment by aciereszko** [comment]
Maybe this just means we are misusing the library. Or have some basic misunderstanding of the usage pattern?

The question is simple. I need to be able for users to purchase subscriptions, and then make sure they are valid, on every app open :)

Help anyone :) ?

**Comment by ArkaneKhan** [comment]
Facing same issue. Any one found any solution?

**Comment by aciereszko** [comment]
So at this point I'm not sure if this is really the issue with the library, or the app store.

Maybe one of the contributed could weight in, maybe we are all missing the library here. Mabye the usage pattern is wrong. When should you wire up the listeners, when you should you store/validate the receipt, etc. @hyochan or other?

**Comment by aciereszko** [comment]
@adambeer any luck solving this?

**Comment by adambeer** [comment]
It seems that this is actually by design. Im not sure why, but it looks like all receipts are sent when initConnection() is called. I just found a handy feature in App Store Connect under Users And Access in the Sandbox Testers section where you push Edit and select your user and you can clear purchase history. This should reset everything auto-renewal and non-consumable wise.

**Comment by aciereszko** [comment]
So when do you do your receipt saving and validation?

**Comment by aciereszko** [comment]
But at some point user needs to make the new purchase, and you do get a receipt which you need to validate and save right? You're not doing that in the purchaseUpdateListener?

**Comment by aciereszko** [comment]
I'm not sure if this will help anyone, but I think in the end you have to expect that sometimes (and most likely this is a practical problem in Sandbox only - where you purchase history will have hundreds and hundreds of records) you will get hundreds of calls to the purchaseUpdateListener. You will get all the past receipts for some reason. It doesn't seem to matter if you call getPurchaseHistory before, or call something else. In my experience, this sometimes happens, right after initConnection and the wiring up of the listener. I've also seen forum posts in other libraries forums as well as just vanilla swift/objc native implementations. People see this, I guess its an app store thing.

You just need to figure out how to handle this in your app. It is a background operation, and maybe its ok to just handle all those receipts and validate them, even if it takes time.

**Comment by YaoHuiJi** [comment]
met the same issue, in my project, I got a lot of currentPurchase object(purchaseUpdateListener called 100+ times), but all of the objects have same "originalTransactionDateIOS" value, but different transactionDate value , these two date are even not the same day. 

and I find that the return value of finishTransaction  is 'undefined', what does it means, is it failed to finish the transaction?  is it the reason that purchaseUpdateListener is called more than 100 times ?

**Comment by kidculli** [comment]
> 

So to be clear this behavior doesn't appear when targeting the production environment ?

**Comment by kidculli** [comment]
> I'm not sure if this will help anyone, but I think in the end you have to expect that sometimes (and most likely this is a practical problem in Sandbox only - where you purchase history will have hundreds and hundreds of records - at least for subscriptions) you will get hundreds of calls to the purchaseUpdateListener. You will get all the past receipts for some reason. It doesn't seem to matter if you call getPurchaseHistory before, or call something else. In my experience, this sometimes happens, right after initConnection and the wiring up of the listener. I've also seen forum posts in other libraries forums as well as just vanilla swift/objc native implementations. People see this, I guess its an app store thing.
> 
> You just need to figure out how to handle this in your app. It is a background operation, and maybe its ok to just handle all those receipts and validate them, even if it takes time.

@aciereszko So to be clear this behaviour only occurs when targeting the sandbox environment ? 
For me I notice that my purchaseUpdatedListener is being called on an already consumed purchase even though I call finishTransaction afterwards, this is occurring against the sandbox environment

**Comment by eneffwork** [comment]
Still facing this issue

**Comment by bmitioglov** [comment]
same here :(

**Comment by andresesfm** [comment]
Can anyone confirm this is still an issue using 8.x.x? 
Seems that this could be caused by A) Calling `initConnection` multiple times or B) because of this: https://stackoverflow.com/a/3633571/570612.
A possible solution for A) is to reject multiple calls to init but for B) looks like you also have to be ready for delayed callbacks.

**Comment by andresesfm** [comment]
It should have been fixed indirectly by https://github.com/dooboolab/react-native-iap/pull/1770

**Comment by dprajapati1179** [comment]
> catch

Still having the same issue in latest release "react-native-iap": "10.0.1",

**Comment by andresesfm** [comment]
I have released 10.0.3 that might resolve this issue by cleaning up promises when calling disconnect: https://github.com/dooboolab/react-native-iap/pull/1910

**Comment by shkatulo** [comment]
It still happens in version 12.4.9

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/blob/main/docs/docs/faq.md#update-listener-called-many-times-on-ios-storekit-1

**Comment by YousefAlramli** [comment]
I'm still having the same issue

**Comment by daibing1976** [comment]
any new update? we have the same problem.

**Comment by sgwanlee** [comment]
I've experienced this when a user upgrades monthly subscription to yearly subscription.

**Comment by erenkulaksiz** [comment]
Still happening in the latest version on iOS. If user have monthly subscription, since sandbox has 5 minute-renew time and user spends 20 minutes while playing around, I get multiple calls to the update listener. I dont event need any updates other than first purchase, I handle expire/cancel webhook logic in my backend with server notifications. Such a strange behaviour.

**Comment by Hamawis** [comment]
@erenkulaksiz were you able to fix this?

**Comment by erenkulaksiz** [comment]
> @erenkulaksiz were you able to fix this?

Nope. Started using revenuecat instead. Handling in app purchases yourself is a quite hassle
