### ISSUE TITLE
seletedOfferIndices non-null error

### ISSUE THREAD

**Issue by khj3132** [dooboolab/react-native-iap#1823]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

When I use `requestSubscription` without `selectedOfferIndices` property, the following error occurs.

`Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter selectedOfferIndices`

The default value of `selectedOfferIndices` is undefined , but it doesn't seem to be optional here.

```
@ReactMethod
    fun buyItemByType(
        type: String,
        skuArr: ReadableArray,
        purchaseToken: String?,
        prorationMode: Int,
        obfuscatedAccountId: String?,
        obfuscatedProfileId: String?,
        selectedOfferIndices: ReadableArray, // New optional parameter in V5
        promise: Promise
    ) {
```

Then, when I set `[-1]` to `selectedOfferIndices` property, the following error occurs.

`offerToken is required for constructing ProductDetailsParams`

**Expected Behavior**

**Screenshots**

**Environment:**

- react-native-iap: 9.0.0-rc.1
- react-native: 0.66.3
- Platforms (iOS, Android, emulator, simulator, device): android / real device(Android 9)

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
Hello @khj3132 . I'm working on this

**Comment by andresesfm** [comment]
`offerToken` is required. The error occurs when trying to build `ProductDetailsParams`:
```
@NonNull
            public BillingFlowParams.ProductDetailsParams build() {
                ...
                zzm.zzc(this.zzb, "offerToken is required for constructing ProductDetailsParams.");
```

**Comment by andresesfm** [comment]
Fixed here: https://github.com/dooboolab/react-native-iap/pull/1825

**Comment by khj3132** [comment]
Thank you @andresesfm I will check it, thanks a lot!

**Comment by andresesfm** [comment]
I have released 9.0.0-rc.2

**Comment by nriccar** [comment]
Hello to all!

Im still getting this error, althought Im sending the proper offerToken from the subscription.

Any help? I have 11.0.7 version

**Comment by andresesfm** [comment]
see Migration guides in documentation, probably not passing an object
