### ISSUE TITLE
"E_IAP_NOT_AVAILABLE" when calling initConnection on react-native-iap

### ISSUE THREAD

**Issue by domuen** [dooboolab/react-native-iap#2084]
I am building a mobile app (React Native) that requires subscriptions to use. I will be using Apple/Google pay on the respective platforms. I would like to request subscriptions with the `react-native-iap` library for React Native

I get the error "E_IAP_NOT_AVAILABLE" when calling the initConnection method from the react-native-iap library. I get this on both iOS and Android

![IMG_1225](https://user-images.githubusercontent.com/76541452/199077556-768181c0-49ea-44f7-bd6a-5b00c1bc0496.png)
![Screenshot from 2022-10-31 00-01-20](https://user-images.githubusercontent.com/76541452/199077573-24123489-9929-4a4e-b248-3552fc00daf5.png)

My setup: `expo@46` `react@18` `react-native@0.69.6` `react-native-iap@12.3.2`

I have tried downgrading react-native-iap to versions `8.0.1` and `7.0.3` (and reinstalling modules) with the same result.

I can't seem to find any questions similar to this issue. Any ideas would be appreciated

**Comment by andresesfm** [comment]
For Android, are you running on the Emulator? (It only works on physical devices).
For Ios, what device/iOS version are you testing with? What Storekit mode are you using?

**Comment by babydough** [comment]
I am testing on physical devices. I am using an iPhone 13 on iOS 15 and Samsung S22 on android 12. I am not using StoreKit. I am going to create subscriptions to the ones I created on AppStore Connect. I can't use any of the methods though because `initConnection` throws that exception

**Comment by andresesfm** [comment]
@babydough The thing that comes to mind is that you might be using ```setup({storekitMode: 'STOREKIT2_MODE'})``` on a device with older iOS. Another option is that IAP purchases are not available on those devices. Are you able to purchase on other apps?

**Comment by LorienHW** [comment]
and on android it throws this error when calling `clearProductsIOS`

**Comment by andresesfm** [comment]
That makes sense. Thank you @LorienHW for your help

**Comment by domuen** [comment]
@LorienHW I just did what you said and logged those values. `RNIapIos` was `null` and `isStorekit2Avaiable()` returned `false`. This is on the latest release. Also note this error happens on Android as well. Do you think this could be an issue with Expo Go or something? I'm not very familiar with native modules or how they interact with Expo

**Comment by LorienHW** [comment]
yeah, so for me RNIapIos is defined, so it never checks `isStorekit2Avaiable()`. i do think its likely that this is somehow related to Expo, however i have never used Expo so i dont know really what it would be. but it kind of seems like the native module has maybe not been built in

**Comment by andresesfm** [comment]
If you are using expo, take a look at: https://stackoverflow.com/a/73159706/570612

**Comment by anishamalde** [comment]
Is there any way to get around the error if you are using expo and don't want to build the project every-time?

**Comment by domuen** [comment]
Just so everyone is aware, I ended up switching to RevenueCat and now use the  `react-native-purchases` library. It is true that I have to build my app every time I want to test a change, which definitely is annoying.

@anishamalde I usually have to comment out any code before I test locally on both libraries. It won't work with Expo Go. At least the code is pretty straight forward once you have everything setup

**Comment by iasreact1** [comment]
@LorienHW @domuen @andresesfm  i used react-native-iap -12.7.2 and i got similar error and got RNIapIos is null and isStorekit2Availabel() is false ...what is the solutions ? please help Sir...

**Comment by andresesfm** [comment]
Could be a problem with pod install?

**Comment by ggchicote** [comment]
@iasreact1 did you fill up the **Agreements, Tax, and Banking** section? It might be the problem. Remember that it takes till 24hs to be accepted.

**Comment by YASH6004** [comment]
this worked for me : https://github.com/dooboolab-community/react-native-iap/issues/1404#issuecomment-1794639457

**Comment by aleksandarbos** [comment]
> If you are using expo, take a look at: https://stackoverflow.com/a/73159706/570612

yup, expo go won't work. thanks, expo development (native) build is required. thanks

**Comment by pashanhenlei** [comment]
> Could be a problem with pod install?

Yes, in my case, I just re-run 'pod install' and make sure the output contains "Installing RNIap", and the error is gone.

**Comment by wesamodeh** [comment]
**SOLVED**

im adding this in my initConnection : 
RNIap.purchaseUpdatedListener(purchase => {
          RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken);
        });
        
fixed when i add a condition :

if (Platform.OS === 'android') {
        RNIap.purchaseUpdatedListener(purchase => {
          RNIap.acknowledgePurchaseAndroid(purchase.purchaseToken);
        });
      }

**Comment by mibrahimmkhann** [comment]
I'm using an iOS emulator with iPhone 14 and iOS 17.5 but still encountering the E_IAP_NOT_AVAILABLE error.

**Comment by Muhammad-Ibrahim-Amjad64** [comment]
I'm using an iOS emulator with iPhone 14 and iOS 17.5 but still encountering the E_IAP_NOT_AVAILABLE error.
