### ISSUE TITLE
iOS: This in-app purchase has already been bought.

### ISSUE THREAD

**Issue by siderakis** [dooboolab/react-native-iap#257]
### Version of react-native-iap
    "react-native-iap": "^2.0.3",

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Makes a purchase

  const purchase = await RNIap.buyProductWithoutFinishTransaction(productId)
      const { transactionReceipt, purchaseToken } = purchase
      sendToServer(transactionReceipt,        {
          onSuccess: () => {
            RNIap.finishTransaction()
            RNIap.consumeAllItems()
          }})

### Actual behavior
Dialog: “This in-app purchase has already been bought”. This is only happening for one purchase, others are working fine. I think the app got in a bad state and I don't see a way to fix it. Other SKUs I can purchase multiple times without issue.

### Tested environment (Emulator? Real Device?)
Device (sandbox)

**Comment by dooboolab** [comment]
@siderakis Yeah strange. I've already patched this problem like told in [stackoverflow](https://stackoverflow.com/questions/34001868/ios-this-in-app-purchase-has-already-been-bought-pop-up) but still occurring in some devices. I am willing to fix this too. What device are you using?

**Comment by dooboolab** [comment]
@siderakis [This](https://stackoverflow.com/questions/18210747/how-to-remove-a-very-old-defunct-in-app-purchase-from-the-transaction-queue) might solve your app in bad state I guess. Could you try?

**Comment by siderakis** [comment]
I tried it and it didn't work. I also reinstalled the app and that didn't help. It's running on an iPad.

**Comment by siderakis** [comment]
I set a breakpoint and it looks like currentQueue.transactions is empty

**Comment by siderakis** [comment]
From SKPaymentQueue.h

```
// Array of unfinished SKPaymentTransactions.  Only valid while the queue has observers.  Updated asynchronously.
@property(nonatomic, readonly) NSArray<SKPaymentTransaction *> *transactions NS_AVAILABLE_IOS(3_0);

@end

```

Maybe I called it too soon

**Comment by siderakis** [comment]
I called the code later in the programs execution and it fixed the issue.

**Comment by JJMoon** [comment]
@siderakis Sorry for bothering. But, what code did you call ?

**Comment by JJMoon** [comment]
@siderakis Yes. That's what I meant in issue #259 .
I think that action can be anywhere after applicationDidBecomeActive.
So, I will expose that method to JS side, that user can call it any time.
Thank you for your advice.

**Comment by sivrihuseyin** [comment]
@JJMoon, I have the same issue, When can we expect a resolution for exposing a method as you mentioned above. Thanks.

**Comment by dooboolab** [comment]
@sivrihuseyin Problem is well known now. We will make the patch this weekend. Thank you to all issuers.

**Comment by dooboolab** [comment]
We've released the expected solution in `2.2.0`. Could you follow [readme](https://github.com/dooboolab/react-native-iap/blob/master/README.md#L317) and try this line of codes?

**Comment by sivrihuseyin** [comment]
Hello Hyo Chan,

Thank you for the information.

I have installed the version 2.2.0 and tried the code. Unfortunately, the
issue is not fixed yet. think that the function, *clearTransaction *has not
been exported. In reactNative environment there is no clearTransaction
function inside RNIap.

I checked the file index.d.ts and I couldn't see the function as
clearTransaction in this. file.

Kind regards,

Huseyin

**Comment by sivrihuseyin** [comment]
Hello Hyo Chan,

I am sorry for the wrong information. IT IS FIXED. There is no problem
anymore.

Thank you for your prompt response and great solution.

Kind regards,

Huseyin

**Comment by leotm** [comment]
For future Googlers upgrading from v2 to v3-5, I found this helpful

https://github.com/dooboolab/react-native-iap/blob/de0fc084966fc4d36a9c45f4e27cb166243d4319/README_DEPRECATED.md
