### ISSUE TITLE
Can not build expo since v13.

### ISSUE THREAD

**Issue by LemireCoding** [dooboolab/react-native-iap#2973]
I can not build expo anymore and keep getting the same error. Pretty sure it is related to react-native-iap as I have not modified anything and just needed to rebuild a development build since it expired. Here is the error I get : 

❌  (node_modules/react-native-iap/ios/IapSerializationUtils.swift:209:40)

  207 |     #if compiler(>=5.10)
  208 |     if #available(iOS 15.2, tvOS 15.2, *) {
> 209 |         result["appTransactionID"] = t.appTransactionID
      |                                        ^ value of type 'Transaction' has no member 'appTransactionID'
  210 |     }
  211 |     #endif
  212 | 

- react-native-iap:  "react-native-iap": "^12.16.2",

Trying to build for development and prod for ios.

**Comment by ivannzme** [comment]
Getting the same issue on react-native-iap - 13.0.2

<img width="1098" height="324" alt="Image" src="https://github.com/user-attachments/assets/7139530d-96de-430a-8fd8-3f4402083b07" />

<img width="630" height="218" alt="Image" src="https://github.com/user-attachments/assets/1c5ef47d-ff74-4f5a-a039-b8565c39b604" />

"react-native": "0.72.17",
"react": "18.2.0",

My bad, the project is on xcode 16.2 which only supports iOS 18.2 SDK

xcodebuild -showsdks
DriverKit SDKs:
	DriverKit 24.2                	-sdk driverkit24.2

**iOS SDKs:
	iOS 18.2                      	-sdk iphoneos18.2**

iOS Simulator SDKs:
	Simulator - iOS 18.2          	-sdk iphonesimulator18.2

macOS SDKs:
	macOS 15.2                    	-sdk macosx15.2
	macOS 15.2                    	-sdk macosx15.2

tvOS SDKs:
	tvOS 18.2                     	-sdk appletvos18.2

tvOS Simulator SDKs:
	Simulator - tvOS 18.2         	-sdk appletvsimulator18.2

visionOS SDKs:
	visionOS 2.2                  	-sdk xros2.2

visionOS Simulator SDKs:
	Simulator - visionOS 2.2      	-sdk xrsimulator2.2

watchOS SDKs:
	watchOS 11.2                  	-sdk watchos11.2

watchOS Simulator SDKs:
	Simulator - watchOS 11.2      	-sdk watchsimulator11.2


**xcodebuild -version
Xcode 16.2
Build version 16C5032a**

**Comment by LemireCoding** [comment]
Can anyone help...

**Comment by luisescorcio** [comment]
I was able to bypass the issue by check if the appTransaction ID is set. Also I've notice an infinite re-render issue on the setSubscriptions so I also made a patch to it. I check if the subscription object changed if not we don't setSubscriptions.

Xcode version 16.2

"react": "18.3.1",
"react-native": "0.76.9",
"expo": "~52.0.47",
"react-native-iap": "13.0.0",

The patch is attached on this comment.

[react-native-iap+13.0.0.patch](https://github.com/user-attachments/files/21532697/react-native-iap%2B13.0.0.patch)

**Comment by hyochan** [comment]
@luisescorcio Thanks for sharing this! I’m currently more focused on maintaining expo-iap, so it’s been tough for me to address everything in react-native-iap as well.

I really appreciate your help with the community here. If your patch works well, would you mind opening a PR for it?

**Comment by hyochan** [comment]
Apologies for the inconvenience caused! 🙏 This issue should be fixed by #2975, and I’ll be releasing **v13.0.3** shortly with the fix included. Thanks for your patience!

**Comment by whidrubeld** [comment]
This problem persists and is observed with version 13.0.4 for Expo 52. It is solved by downgrading to 12.16.2.

With Expo 53 and version 12.16.2, 12.16.4 or 13.0.4 - there is no problem.

**Comment by ngdbao** [comment]
> This problem persists and is observed with version 13.0.4 for Expo 52. It is solved by downgrading to 12.16.2.
> 
> With Expo 53 and version 12.16.2, 12.16.4 or 13.0.4 - there is no problem.

it doesn't work for me, unless I upgrade Xcode to 16.4
